/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controls.Szemely;
import Controls.Tranzakcio;
import Controls.Vagyon;
import Model.DB;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ContainerAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HorvathAttila
 */
public class TranzakcioPanel extends JPanel implements ActionListener {

    JButton Add = new JButton();
    JButton Mod = new JButton();
    JButton Del = new JButton();
    ImageIcon addIcon = new ImageIcon(new ImageIcon("src/Icons/insert.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
    ImageIcon modifyIcon = new ImageIcon(new ImageIcon("src/Icons/edit.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
    ImageIcon deleteIcon = new ImageIcon(new ImageIcon("src/Icons/delete.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
    JTable TransactionTable = new JTable(0, 19);
    DefaultTableModel ModelTable = (DefaultTableModel) TransactionTable.getModel();
    DB TransactionDB = new DB();
    Tranzakcio TranzakcioInstance = new Tranzakcio();
    Vagyon VagyonInstance = new Vagyon();
    ArrayList<Tranzakcio> Tranzakciok = null;
    String TranzakcioParam;
    JPanel northPanel = new JPanel();

    //<editor-fold defaultstate="collapsed" desc="Táblázat készítés metódus">
    public void refreshTable() {
        Tranzakciok = TransactionDB.geTranzakcioParam(TranzakcioParam);
        Object[] row = new Object[19];
        ModelTable.setRowCount(0);
        for (int i = 0; i < Tranzakciok.size(); i++) {
            row[0] = Tranzakciok.get(i).getNev();
            row[1] = Tranzakciok.get(i).getKategoriaNev();
            row[2] = Tranzakciok.get(i).getOsszeg();
            row[3] = Tranzakciok.get(i).getPenzTipus();
            row[4] = Tranzakciok.get(i).getDatum();
            row[5] = Tranzakciok.get(i).getVagyonNev1();
            row[6] = Tranzakciok.get(i).getSzemelyNev1();
            row[7] = Tranzakciok.get(i).getVagyonNev2();
            row[8] = Tranzakciok.get(i).getSzemelyNev2();
            row[9] = Tranzakciok.get(i).getTranzakcioRendszeressegNev();
            row[10] = Tranzakciok.get(i).getTRID();
            row[11] = Tranzakciok.get(i).getKategoria();
            row[12] = Tranzakciok.get(i).getPenznem();
            row[13] = Tranzakciok.get(i).getVagyonID1();
            row[14] = Tranzakciok.get(i).getVagyonID2();
            row[15] = Tranzakciok.get(i).getTranzakcioRendszeresseg();
            row[16] = Tranzakciok.get(i).getTranzakcioTipus();
            row[17] = Tranzakciok.get(i).getTipusNev1();
            row[18] = Tranzakciok.get(i).getTipusNev2();
            ModelTable.addRow(row);
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TransactionTable.setFocusable(false);
        TransactionTable.setSelectionBackground(Color.lightGray);
        TransactionTable.setFont(new Font("Arial", Font.BOLD, 12));
        TransactionTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 17));
        switch (TranzakcioParam) {
            case "1":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Pénzügyi eszközbe");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                break;

            case "2":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Pénzügyi eszközbe");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                break;

            case "3":
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(1).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(9).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(0).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(2).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénzn");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setMaxWidth(TransactionTable.getColumnModel().getColumn(3).getWidth());
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(3).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setMaxWidth(TransactionTable.getColumnModel().getColumn(4).getWidth());
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(4).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Pénzügyi eszközbe");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(5).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(6).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(7).setHeaderValue("Pénzügyi eszközből");
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(7).setPreferredWidth(TransactionTable.getColumnModel().getColumn(7).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(7).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(8).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(8).setPreferredWidth(TransactionTable.getColumnModel().getColumn(8).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(8).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(8).sizeWidthToFit();
                break;
            case "4":
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(1).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(0).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(2).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(3).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(4).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Vagyontárgy");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(5).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(6).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "5":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Vagyontárgy");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "6":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Vagyontárgy");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "7":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "8":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Dátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "9":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Tőkecsökkenés");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Végdátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "10":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Törlesztés");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Végdátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "11":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Végdátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
            case "12":
                TransactionTable.getColumnModel().getColumn(7).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(7).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(8).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(10).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(11).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(12).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(13).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(14).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(15).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(16).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(17).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMinWidth(0);
                TransactionTable.getColumnModel().getColumn(18).setMaxWidth(0);
                TransactionTable.getColumnModel().getColumn(0).setHeaderValue("Tranzakció");
                TransactionTable.getColumnModel().getColumn(0).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(0).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(0).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(1).setHeaderValue("Kategória");
                TransactionTable.getColumnModel().getColumn(1).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(1).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(1).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(2).setHeaderValue("Összeg");
                TransactionTable.getColumnModel().getColumn(2).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(2).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(2).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(3).setHeaderValue("Pénznem");
                TransactionTable.getColumnModel().getColumn(3).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(3).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(3).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(4).setHeaderValue("Végdátum");
                TransactionTable.getColumnModel().getColumn(4).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(4).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(4).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(5).setHeaderValue("Eszköz");
                TransactionTable.getColumnModel().getColumn(5).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(5).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(5).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(6).setHeaderValue("Személy");
                TransactionTable.getColumnModel().getColumn(6).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(6).setPreferredWidth(TransactionTable.getColumnModel().getColumn(1).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(6).sizeWidthToFit();
                TransactionTable.getColumnModel().getColumn(9).setHeaderValue("Rendszeresség");
                TransactionTable.getColumnModel().getColumn(9).setMinWidth(5);
                TransactionTable.getColumnModel().getColumn(9).setPreferredWidth(TransactionTable.getColumnModel().getColumn(9).getWidth() + 1);
                TransactionTable.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
                TransactionTable.getColumnModel().getColumn(9).sizeWidthToFit();
                break;
        }
        TransactionTable.getTableHeader().resizeAndRepaint();
        TransactionTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TransactionTable.setShowVerticalLines(false);
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Konstruktor metódus">  
    public TranzakcioPanel(String TranzakcioParam) {

        this.TranzakcioParam = TranzakcioParam;
        this.setLayout((new BorderLayout()));
        Add.setIcon(addIcon);
        Mod.setIcon(modifyIcon);
        Del.setIcon(deleteIcon);
        Add.addActionListener(this);
        Mod.addActionListener(this);
        Del.addActionListener(this);
        refreshTable();
        JScrollPane scrollPane = new JScrollPane(TransactionTable);
        northPanel.add(Add);
        northPanel.add(Mod);
        northPanel.add(Del);
        this.add(northPanel, BorderLayout.NORTH);
        this.add(scrollPane, BorderLayout.CENTER);
        this.setBorder(BorderFactory.createEmptyBorder(150, 150, 150, 150));
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Eseménykezelés"> 
    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == Add) {

            TranzakcioMuvelet TransactionAction = new TranzakcioMuvelet(parseInt(TranzakcioParam));
            TransactionAction.setupAdd();
            TransactionAction.mainFrameAdd.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    refreshTable();
                }
            });
        }
        if (e.getSource() == Mod) {
            if (TransactionTable.getSelectedRow() >= 0) {
                TranzakcioMuvelet TransactionAction = new TranzakcioMuvelet(parseInt(TranzakcioParam));
                TranzakcioInstance.setNev(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 0).toString());
                TranzakcioInstance.setKategoriaNev(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 1).toString());
                TranzakcioInstance.setOsszeg((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 2));
                TranzakcioInstance.setPenzTipus(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 3).toString());
                TranzakcioInstance.setDatum((LocalDate) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 4));
                TranzakcioInstance.setVagyonNev1(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 5).toString());
                TranzakcioInstance.setVagyonNev2(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 7).toString());
                TranzakcioInstance.setSzemelyNev1(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 6).toString());
                TranzakcioInstance.setSzemelyNev2(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 8).toString());
                TranzakcioInstance.setTranzakcioRendszeressegNev(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 9).toString());
                TranzakcioInstance.setTRID((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 10));
                TranzakcioInstance.setKategoria((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 11));
                TranzakcioInstance.setPenznem((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 12));
                TranzakcioInstance.setVagyonID1((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 13));
                TranzakcioInstance.setVagyonID2((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 14));
                TranzakcioInstance.setTranzakcioRendszeresseg((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 15));
                TranzakcioInstance.setTranzakcioTipus((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 16));
                TranzakcioInstance.setTipusNev1(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 17).toString());
                TranzakcioInstance.setTipusNev2(TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 18).toString());
                TransactionAction.setupMod(TranzakcioInstance);
                TransactionAction.mainFrameMod.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        refreshTable();
                    }
                });
            }
        }
        if (e.getSource() == Del) {
            TranzakcioMuvelet TransactionAction = new TranzakcioMuvelet();
            if (TransactionTable.getSelectedRow() >= 0) {
                TranzakcioInstance.setTRID((int) TransactionTable.getModel().getValueAt(TransactionTable.getSelectedRow(), 10));
                TransactionAction.setupDel(TranzakcioInstance);
                if (TransactionAction.deleteEvent == 1) {
                    refreshTable();
                }
            }
        }
    }
    //</editor-fold>
}
